checksumBehavior: update

nodeLinker: node-modules

npmAlwaysAuth: true

npmPublishRegistry: 'https://europe-west8-npm.pkg.dev/open-gto-2/goat/'

npmRegistryServer: 'https://europe-west8-npm.pkg.dev/open-gto-2/goat/'
